using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace TestConsoleApp.Generators.Tests;

public sealed class CommandRegistrationGeneratorTests
{
    // Minimal stub definitions that satisfy the generator's semantic checks.
    private const string SupportSource = """
        namespace TestConsoleApp.Application.Abstractions
        {
            public interface IMenuCommand
            {
                string Title { get; }
                System.Threading.Tasks.Task ExecuteAsync(System.Threading.CancellationToken cancellationToken = default);
            }

            [System.AttributeUsage(System.AttributeTargets.Class)]
            public sealed class SubMenuAttribute : System.Attribute
            {
                public SubMenuAttribute(string name) { }
                public string Name { get; }
            }

            public static class CommandRegistry
            {
                public static void Register(IMenuCommand command) { }
            }
        }

        namespace TestConsoleApp.Presentation.Menus
        {
            public sealed class SubMenuCommand : TestConsoleApp.Application.Abstractions.IMenuCommand
            {
                public SubMenuCommand(string title, System.Collections.Generic.IReadOnlyList<TestConsoleApp.Application.Abstractions.IMenuCommand> commands) { }
                public string Title => "";
                public System.Threading.Tasks.Task ExecuteAsync(System.Threading.CancellationToken cancellationToken = default)
                    => System.Threading.Tasks.Task.CompletedTask;
            }
        }
        """;

    private static (ImmutableArray<Diagnostic> Diagnostics, ImmutableArray<GeneratedSourceResult> Sources)
        RunGenerator(string testSource)
    {
        var references = ((string?)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES"))!
            .Split(Path.PathSeparator)
            .Select(p => (MetadataReference)MetadataReference.CreateFromFile(p));

        var compilation = CSharpCompilation.Create(
            "TestAssembly",
            [CSharpSyntaxTree.ParseText(SupportSource), CSharpSyntaxTree.ParseText(testSource)],
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        GeneratorDriver driver = CSharpGeneratorDriver.Create(
            new ISourceGenerator[] { new CommandRegistrationGenerator().AsSourceGenerator() });
        driver = driver.RunGenerators(compilation);

        var result = driver.GetRunResult().Results[0];
        return (result.Diagnostics, result.GeneratedSources);
    }

    [Fact]
    public void ProducesNoOutput_WhenNoCommandsInSource()
    {
        var (_, sources) = RunGenerator("public class NotACommand { }");

        Assert.Empty(sources);
    }

    [Fact]
    public void GeneratesRegistration_ForSingleStandaloneCommand()
    {
        var source = """
            using TestConsoleApp.Application.Abstractions;
            namespace MyCommands
            {
                public sealed class FooCommand : IMenuCommand
                {
                    public string Title => "Foo";
                    public System.Threading.Tasks.Task ExecuteAsync(System.Threading.CancellationToken ct = default)
                        => System.Threading.Tasks.Task.CompletedTask;
                }
            }
            """;

        var (_, sources) = RunGenerator(source);

        Assert.Single(sources);
        Assert.Contains("CommandRegistry.Register(new FooCommand());", sources[0].SourceText.ToString());
    }

    [Fact]
    public void GeneratedFile_HasCorrectHintName()
    {
        var source = """
            using TestConsoleApp.Application.Abstractions;
            namespace MyCommands
            {
                public sealed class FooCommand : IMenuCommand
                {
                    public string Title => "Foo";
                    public System.Threading.Tasks.Task ExecuteAsync(System.Threading.CancellationToken ct = default)
                        => System.Threading.Tasks.Task.CompletedTask;
                }
            }
            """;

        var (_, sources) = RunGenerator(source);

        Assert.Equal("CommandRegistrationInitializer.g.cs", sources[0].HintName);
    }

    [Fact]
    public void GeneratedSource_ContainsAutoGeneratedComment()
    {
        var source = """
            using TestConsoleApp.Application.Abstractions;
            namespace MyCommands
            {
                public sealed class FooCommand : IMenuCommand
                {
                    public string Title => "Foo";
                    public System.Threading.Tasks.Task ExecuteAsync(System.Threading.CancellationToken ct = default)
                        => System.Threading.Tasks.Task.CompletedTask;
                }
            }
            """;

        var (_, sources) = RunGenerator(source);

        Assert.Contains("// <auto-generated/>", sources[0].SourceText.ToString());
    }

    [Fact]
    public void GeneratedSource_ContainsNullableEnable()
    {
        var source = """
            using TestConsoleApp.Application.Abstractions;
            namespace MyCommands
            {
                public sealed class FooCommand : IMenuCommand
                {
                    public string Title => "Foo";
                    public System.Threading.Tasks.Task ExecuteAsync(System.Threading.CancellationToken ct = default)
                        => System.Threading.Tasks.Task.CompletedTask;
                }
            }
            """;

        var (_, sources) = RunGenerator(source);

        Assert.Contains("#nullable enable", sources[0].SourceText.ToString());
    }

    [Fact]
    public void GeneratedSource_ContainsModuleInitializerAttribute()
    {
        var source = """
            using TestConsoleApp.Application.Abstractions;
            namespace MyCommands
            {
                public sealed class FooCommand : IMenuCommand
                {
                    public string Title => "Foo";
                    public System.Threading.Tasks.Task ExecuteAsync(System.Threading.CancellationToken ct = default)
                        => System.Threading.Tasks.Task.CompletedTask;
                }
            }
            """;

        var (_, sources) = RunGenerator(source);

        Assert.Contains("[ModuleInitializer]", sources[0].SourceText.ToString());
    }

    [Fact]
    public void StandaloneCommands_AreOrderedAlphabetically()
    {
        var source = """
            using TestConsoleApp.Application.Abstractions;
            namespace MyCommands
            {
                public sealed class ZebraCommand : IMenuCommand
                {
                    public string Title => "Zebra";
                    public System.Threading.Tasks.Task ExecuteAsync(System.Threading.CancellationToken ct = default)
                        => System.Threading.Tasks.Task.CompletedTask;
                }
                public sealed class AlphaCommand : IMenuCommand
                {
                    public string Title => "Alpha";
                    public System.Threading.Tasks.Task ExecuteAsync(System.Threading.CancellationToken ct = default)
                        => System.Threading.Tasks.Task.CompletedTask;
                }
            }
            """;

        var (_, sources) = RunGenerator(source);

        var text = sources[0].SourceText.ToString();
        Assert.True(
            text.IndexOf("new AlphaCommand()", StringComparison.Ordinal) <
            text.IndexOf("new ZebraCommand()", StringComparison.Ordinal),
            "AlphaCommand should be registered before ZebraCommand");
    }

    [Fact]
    public void GeneratesSubMenuCommand_ForCommandsWithSubMenuAttribute()
    {
        var source = """
            using TestConsoleApp.Application.Abstractions;
            namespace MyCommands
            {
                [SubMenu("Tools")]
                public sealed class ToolCommand : IMenuCommand
                {
                    public string Title => "Tool";
                    public System.Threading.Tasks.Task ExecuteAsync(System.Threading.CancellationToken ct = default)
                        => System.Threading.Tasks.Task.CompletedTask;
                }
            }
            """;

        var (_, sources) = RunGenerator(source);

        var text = sources[0].SourceText.ToString();
        Assert.Contains("new SubMenuCommand(\"Tools\"", text);
        Assert.Contains("new ToolCommand()", text);
    }

    [Fact]
    public void GeneratesOneSubMenuCommand_WhenMultipleCommandsShareSameGroup()
    {
        var source = """
            using TestConsoleApp.Application.Abstractions;
            namespace MyCommands
            {
                [SubMenu("Utils")]
                public sealed class ACommand : IMenuCommand
                {
                    public string Title => "A";
                    public System.Threading.Tasks.Task ExecuteAsync(System.Threading.CancellationToken ct = default)
                        => System.Threading.Tasks.Task.CompletedTask;
                }
                [SubMenu("Utils")]
                public sealed class BCommand : IMenuCommand
                {
                    public string Title => "B";
                    public System.Threading.Tasks.Task ExecuteAsync(System.Threading.CancellationToken ct = default)
                        => System.Threading.Tasks.Task.CompletedTask;
                }
            }
            """;

        var (_, sources) = RunGenerator(source);

        var text = sources[0].SourceText.ToString();
        Assert.Equal(1, CountOccurrences(text, "new SubMenuCommand("));
        Assert.Contains("new ACommand()", text);
        Assert.Contains("new BCommand()", text);
    }

    [Fact]
    public void GeneratedSource_IncludesSubMenuCommandUsing_WhenGroupedCommandsExist()
    {
        var source = """
            using TestConsoleApp.Application.Abstractions;
            namespace MyCommands
            {
                [SubMenu("Group")]
                public sealed class GroupedCommand : IMenuCommand
                {
                    public string Title => "G";
                    public System.Threading.Tasks.Task ExecuteAsync(System.Threading.CancellationToken ct = default)
                        => System.Threading.Tasks.Task.CompletedTask;
                }
            }
            """;

        var (_, sources) = RunGenerator(source);

        Assert.Contains("using TestConsoleApp.Presentation.Menus;", sources[0].SourceText.ToString());
    }

    [Fact]
    public void GeneratedSource_DoesNotIncludeSubMenuCommandUsing_WhenNoGroupedCommandsExist()
    {
        var source = """
            using TestConsoleApp.Application.Abstractions;
            namespace MyCommands
            {
                public sealed class StandaloneCommand : IMenuCommand
                {
                    public string Title => "S";
                    public System.Threading.Tasks.Task ExecuteAsync(System.Threading.CancellationToken ct = default)
                        => System.Threading.Tasks.Task.CompletedTask;
                }
            }
            """;

        var (_, sources) = RunGenerator(source);

        Assert.DoesNotContain("using TestConsoleApp.Presentation.Menus;", sources[0].SourceText.ToString());
    }

    [Fact]
    public void ExcludesAbstractClasses()
    {
        var source = """
            using TestConsoleApp.Application.Abstractions;
            namespace MyCommands
            {
                public abstract class AbstractCommand : IMenuCommand
                {
                    public abstract string Title { get; }
                    public abstract System.Threading.Tasks.Task ExecuteAsync(System.Threading.CancellationToken ct = default);
                }
            }
            """;

        var (_, sources) = RunGenerator(source);

        Assert.Empty(sources);
    }

    [Fact]
    public void ExcludesClassesWithoutPublicParameterlessConstructor()
    {
        var source = """
            using TestConsoleApp.Application.Abstractions;
            namespace MyCommands
            {
                public sealed class NoDefaultCtorCommand : IMenuCommand
                {
                    public NoDefaultCtorCommand(string value) { }
                    public string Title => "Test";
                    public System.Threading.Tasks.Task ExecuteAsync(System.Threading.CancellationToken ct = default)
                        => System.Threading.Tasks.Task.CompletedTask;
                }
            }
            """;

        var (_, sources) = RunGenerator(source);

        Assert.Empty(sources);
    }

    [Fact]
    public void EscapesDoubleQuotesInSubMenuName()
    {
        var source = """"
            using TestConsoleApp.Application.Abstractions;
            namespace MyCommands
            {
                [SubMenu("Say \"Hello\"")]
                public sealed class QuoteCommand : IMenuCommand
                {
                    public string Title => "Q";
                    public System.Threading.Tasks.Task ExecuteAsync(System.Threading.CancellationToken ct = default)
                        => System.Threading.Tasks.Task.CompletedTask;
                }
            }
            """";

        var (_, sources) = RunGenerator(source);

        Assert.Contains("Say \\\"Hello\\\"", sources[0].SourceText.ToString());
    }

    [Fact]
    public void EscapesBackslashesInSubMenuName()
    {
        var source = """
            using TestConsoleApp.Application.Abstractions;
            namespace MyCommands
            {
                [SubMenu("Path\\Sub")]
                public sealed class BackslashCommand : IMenuCommand
                {
                    public string Title => "P";
                    public System.Threading.Tasks.Task ExecuteAsync(System.Threading.CancellationToken ct = default)
                        => System.Threading.Tasks.Task.CompletedTask;
                }
            }
            """;

        var (_, sources) = RunGenerator(source);

        Assert.Contains(@"Path\\Sub", sources[0].SourceText.ToString());
    }

    [Fact]
    public void ProducesNoDiagnosticErrors()
    {
        var source = """
            using TestConsoleApp.Application.Abstractions;
            namespace MyCommands
            {
                public sealed class FooCommand : IMenuCommand
                {
                    public string Title => "Foo";
                    public System.Threading.Tasks.Task ExecuteAsync(System.Threading.CancellationToken ct = default)
                        => System.Threading.Tasks.Task.CompletedTask;
                }
            }
            """;

        var (diagnostics, _) = RunGenerator(source);

        Assert.Empty(diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error));
    }

    private static int CountOccurrences(string text, string pattern)
    {
        var count = 0;
        var index = 0;
        while ((index = text.IndexOf(pattern, index, StringComparison.Ordinal)) >= 0)
        {
            count++;
            index += pattern.Length;
        }
        return count;
    }
}
