using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace TestConsoleApp.Generators;

[Generator]
public sealed class CommandRegistrationGenerator : IIncrementalGenerator
{
    private const string InterfaceName = "IMenuCommand";
    private const string InterfaceNamespace = "TestConsoleApp.Application.Abstractions";
    private const string SubMenuAttributeName = "SubMenuAttribute";
    private const string SubMenuCommandNamespace = "TestConsoleApp.Presentation.Menus";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var commandModels = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                static (ctx, _) => GetCommandModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!.Value)
            .Collect();

        context.RegisterSourceOutput(commandModels, static (ctx, models) => Emit(ctx, models));
    }

    private static CommandModel? GetCommandModel(GeneratorSyntaxContext context)
    {
        var symbol = context.SemanticModel.GetDeclaredSymbol(context.Node) as INamedTypeSymbol;

        if (symbol is null || symbol.IsAbstract || symbol.IsGenericType)
            return null;

        var implementsInterface = symbol.AllInterfaces.Any(i =>
            i.Name == InterfaceName &&
            i.ContainingNamespace.ToDisplayString() == InterfaceNamespace);

        if (!implementsInterface)
            return null;

        var hasParameterlessConstructor = symbol.InstanceConstructors.Any(c =>
            c.Parameters.IsEmpty &&
            c.DeclaredAccessibility == Accessibility.Public);

        if (!hasParameterlessConstructor)
            return null;

        var subMenuAttr = symbol.GetAttributes().FirstOrDefault(a =>
            a.AttributeClass?.Name == SubMenuAttributeName &&
            a.AttributeClass.ContainingNamespace.ToDisplayString() == InterfaceNamespace);

        var subMenuGroup = subMenuAttr?.ConstructorArguments.Length > 0
            ? subMenuAttr.ConstructorArguments[0].Value as string
            : null;

        return new CommandModel(
            symbol.Name,
            symbol.ContainingNamespace.ToDisplayString(),
            subMenuGroup);
    }

    private static void Emit(SourceProductionContext context, ImmutableArray<CommandModel> models)
    {
        if (models.IsEmpty)
            return;

        var standalone = models
            .Where(m => m.SubMenuGroup is null)
            .OrderBy(m => m.TypeName)
            .ToList();

        var grouped = models
            .Where(m => m.SubMenuGroup is not null)
            .GroupBy(m => m.SubMenuGroup!)
            .OrderBy(g => g.Key)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine($"using {InterfaceNamespace};");

        if (grouped.Count > 0)
            sb.AppendLine($"using {SubMenuCommandNamespace};");

        foreach (var ns in models
            .Select(m => m.Namespace)
            .Where(ns => ns != InterfaceNamespace)
            .Distinct()
            .OrderBy(ns => ns))
        {
            sb.AppendLine($"using {ns};");
        }

        sb.AppendLine();
        sb.AppendLine("namespace TestConsoleApp.Generated;");
        sb.AppendLine();
        sb.AppendLine("internal static class CommandRegistrationInitializer");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void RegisterAll()");
        sb.AppendLine("    {");

        foreach (var model in standalone)
            sb.AppendLine($"        CommandRegistry.Register(new {model.TypeName}());");

        foreach (var group in grouped)
        {
            var items = string.Join(", ", group.OrderBy(m => m.TypeName).Select(m => $"new {m.TypeName}()"));
            sb.AppendLine($"        CommandRegistry.Register(new SubMenuCommand(\"{EscapeString(group.Key)}\", [{items}]));");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("CommandRegistrationInitializer.g.cs", sb.ToString());
    }

    private static string EscapeString(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private readonly record struct CommandModel(string TypeName, string Namespace, string? SubMenuGroup);
}
