using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace TestConsoleApp.Generators;

[Generator]
public sealed class CommandRegistrationGenerator : IIncrementalGenerator
{
    private const string InterfaceName = "IMenuCommand";
    private const string InterfaceNamespace = "TestConsoleApp.Application.Abstractions";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var commandTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                transform: static (ctx, _) => GetCommandType(ctx))
            .Where(static t => t is not null)
            .Collect();

        context.RegisterSourceOutput(commandTypes, static (ctx, types) => Emit(ctx, types!));
    }

    private static INamedTypeSymbol? GetCommandType(GeneratorSyntaxContext context)
    {
        var symbol = context.SemanticModel.GetDeclaredSymbol(context.Node) as INamedTypeSymbol;

        if (symbol is null || symbol.IsAbstract || symbol.IsGenericType)
            return null;

        return symbol.AllInterfaces.Any(i =>
            i.Name == InterfaceName &&
            i.ContainingNamespace.ToDisplayString() == InterfaceNamespace)
                ? symbol
                : null;
    }

    private static void Emit(SourceProductionContext context, ImmutableArray<INamedTypeSymbol> types)
    {
        if (types.IsEmpty)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine($"using {InterfaceNamespace};");

        foreach (var ns in types
            .Select(t => t.ContainingNamespace.ToDisplayString())
            .Where(ns => ns != InterfaceNamespace)
            .Distinct()
            .OrderBy(ns => ns))
        {
            sb.AppendLine($"using {ns};");
        }

        sb.AppendLine();
        sb.AppendLine("namespace TestConsoleApp.Generated;");
        sb.AppendLine();
        sb.AppendLine("internal static class CommandRegistrationInitializer");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void RegisterAll()");
        sb.AppendLine("    {");

        foreach (var type in types.OrderBy(t => t.Name))
            sb.AppendLine($"        CommandRegistry.Register(new {type.Name}());");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("CommandRegistrationInitializer.g.cs", sb.ToString());
    }
}
